### ISSUE TITLE
JSON string as secret

### ISSUE THREAD

**Issue by visini** [unfor19/githubsecrets#22]
Hi there, thanks for your awesome project! I'm trying to implement it to store a complicated, "flat" JSON string:

```bash
ghs secret-apply -p my_profile -r my_repo -s MY_SECRET_KEY -v {"foo": "bar", ...}
```

The "flat" JSON string is created like this: `jq --compact-output '.' file.json`

When pasting my JSON manually in the repo settings, my workflows run without any issues. However, when creating the secret with `ghs`, the workflow fails due to `jq` complaining that the JSON is malformed:

```bash
parse error: Invalid numeric literal at line 1, column 19
```

It's hard to know what's happening, since I obviously can't echo the secret and check the logs if the formatting is changed somewhere (maybe the quotes are urlencoded? maybe some weird whitespace issue?)...

Do you have an idea what I can try to find out what's happening? Many thanks!

**Comment by unfor19** [comment]
Thank you for your feedback!
Have you tried surrounding the value with single quotes ? Like this - `-v '{ ... }'` 
I haven't tested it but it might work, and if it doesn't I'll add support for JSON objects

**Comment by unfor19** [comment]
@visini - after doing some tests, it seems like it's related to GitHub Actions and jq.



```yaml
      - name: JSON secret
        env: 
          ENV_TEST_JSON: ${{ secrets['TEST_JSON'] }}
        run: |
           # jq --version # 1.5
           # echo '${{ secrets['TEST_JSON'] }}' | jq
           # echo $ENV_TEST_JSON | jq

           curl -L -o jq https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
           chmod +x jq
           sudo mv jq /usr/local/bin
           jq --version # 1.6           
           # echo '${{ secrets['TEST_JSON'] }}' | jq  # parse error: Invalid literal at line 1, column 6
           echo $ENV_TEST_JSON | jq                       # works
           echo "$ENV_TEST_JSON" | jq                    # works
           echo '$ENV_TEST_JSON' | jq                  # doesn't work
```
